#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ ! -f "/config/credentials.json" ]; then
    cp /defaults/credentials.json /config/credentials.json
fi

if [ ! -f "/config/db.sqlite3" ]; then
    python3 /app/conreq/manage.py migrate
    python3 /app/conreq/manage.py createsuperuser --noinput
fi

# permissions
chown -R abc:abc \
    /app \
    /config
