#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd /app/conreq || return

python3 ./manage.py migrate --noinput
python3 ./manage.py collectstatic --link --noinput
python3 ./manage.py compress
s6-setuidgid abc python3 ./manage.py run_huey --quiet &

# permissions
chown -R abc:abc \
    /app \
    /config
